# Generated by Django 2.2.14 on 2021-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210419_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('J', 'Jabon'), ('C', 'Crema'), ('S', 'Shampoo'), ('E', 'Emulsiones')], max_length=2),
        ),
    ]
