# Generated by Django 2.2.14 on 2021-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210419_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'tradicional'), ('S', 'nuevo'), ('D', 'promo')], max_length=1),
        ),
    ]
