# Generated by Django 2.2.14 on 2021-04-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210419_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primary', 'tradicional'), ('S', 'secondary'), ('D', 'danger')], max_length=15),
        ),
    ]
