# Generated by Django 2.2.14 on 2021-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210419_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.TextField(choices=[('tradicional', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=15),
        ),
    ]
