# Generated by Django 2.2.14 on 2021-04-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210419_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('T', 'tradicional'), ('N', 'nuevo'), ('P', 'promo')], max_length=100),
        ),
    ]
