# Generated by Django 2.2.14 on 2021-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210419_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primary', 'tradicional'), ('secondary', 'nuevo'), ('danger', 'promo')], max_length=100),
        ),
    ]
