# Generated by Django 2.2.14 on 2021-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210419_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primary', 'tradicional'), ('secondary', 'NUEVO'), ('danger', 'PROMO')], max_length=100),
        ),
    ]
