# Generated by Django 2.2.14 on 2021-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210419_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
