# Generated by Django 2.2.7 on 2022-09-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_description_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('V', 'Placa de Video'), ('C', 'Combos'), ('A', 'Accesorios')], max_length=2),
        ),
    ]
