# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - haikucosmeticanatural

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://marcoscontainer1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2d0eec480989481e95e79fb4e44530c5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c76cd9331d8943a4bc11aa0a53200eff }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: marcoscontainer1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d0eec480989481e95e79fb4e44530c5 }}/django-haiku:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'haikucosmeticanatural'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_adf9624745dc4d448cbd91d0c1e1348e }}
        images: 'marcoscontainer1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d0eec480989481e95e79fb4e44530c5 }}/django-haiku:${{ github.sha }}'